development:
  adapter: postgresql
  encoding: unicode
  database: whitestream_development
  pool: 5
  username: luke
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: whitestream_test
  pool: 5
  username: luke
  password: